### PR TITLE
initial dreamhouse styling for login and main views

### PR DESCRIPTION
**Pull request by lynnandtonic**
@crcastle Here's some initial styling for you. I wasn't sure how to get the player and playlist to show up, so I put in a bunch of static markup for now. Does that work for you to hook things up?

I still need to do some cleanup and responsive stuff, but this should be good at least to get things working and showable.

Also, will you be creating the other playlist/form view? I think it'd be easier for me if you create that and then I drop in markup/styles. 

Let me know if anything seems off. I probably won't be able to pick back up on this until this afternoon.

### CODE REVIEW

**Comment by lynnandtonic** [comment]
Also, I wasn't sure if I should commit the changes we made to package.json and auth.js. Should I?

**Comment by crcastle** [comment]
This looks great @lynnandtonic!  I have give a webinar at 11, but after lunch I'll add the changes to this branch so it's "live".  I think that should be pretty straight forward based on what you've provided.  I'll let you know if I bork up any styling and need your help in the process.

Can you make the `auth.js` changes in another branch?  A `get-it-working` branch?  And can you remind me what changes we made to `package.json`?  Or did you mean the changes to `node_modules/react-scripts`?

**Comment by lynnandtonic** [comment]
@crcastle Yup, I can do that. So I think in the `package.json` we did this:

```
"sass-dev": "node-sass --watch --include-path 'node_modules/bourbon-neat/app/assets/stylesheets'  src/scss/style.scss --output src"
```

**Comment by crcastle** [comment]
Oh yeah, please add `package.json` to the other branch too.  Off to webinar prep now...

**Pull request merged**
